name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Use website.js ${{ matrix.node.version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node.version }}
    - run: |
        npm i
        pm2 stop 1
        pm2 start 1
        pm2 save
